name: Build Risu Asset Extractor

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    # 1. 저장소 코드 체크아웃
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Python 환경 설정
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 3. 의존성 설치
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. PyInstaller로 애플리케이션 빌드 (하나로 통합된 단계)
    - name: Build with PyInstaller
      run: pyinstaller --onefile --windowed --name RisuAssetExtractor main_ui.py

    # 5. 빌드 결과물 업로드
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: RisuAssetExtractor-${{ matrix.os }}
        path: dist/*